on:
  push:
    branches:
      - master

name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.organization=robertdpowell
          -Dsonar.projectKey=adventofcode2022
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARTOKEN }}
